# Generated by Django 5.2.1 on 2025-05-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_topic_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='host',
        ),
    ]
